---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: "create ansibl directory"
    file: dest=/home/bazar/gid state=directory owner=bazar group=bazar mode=0777

  - name: "Clone git repository"
    git:
      repo: "https://github.com/Sergo2019/sergo.git"
      dest: /home/bazar/gid
      version: master
      update: yes
      accept_hostkey: no
    become: yes
    become_user: bazar
    register: cloned
