---
- name: Jetson
  hosts: all
  become: yes
  become_method: sudo
  become_user: hiden

  tasks:

  - name: "install pexpect"
    pip:
      name: pexpect
    become: yes
    become_user: hiden

  - name: "openalpr-licenseregister"
    expect:
      command: docker run -P -v openalpr-vol1-config:/etc/openalpr/ -it openalpr/commercial-agent:2.7.102-jetson openalpr-licenseregister
      responses:
       'Enter your account e-mail: ': 'test666@mmc.kg'
       'Enter your password: ': '2204Jv05'
      echo: yes
    become: yes

