---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: "cd"
    raw: cd /home/bazar/git

  - name: "rm"
    raw: rm -rf  ansibl

  - git:
#      repo=https://sergo2019:2204Jv05@github.com/Sergo2019/ansibl.git
      repo="https://github.com/Sergo2019/sergo.git"
      dest='/home/bazar/git/ansibl'
      ssh_opts="-o Port=22"
      accept_hostkey=no
#      force=yes
#    become: yes
#    become_user: bazar

  - name: "cd ansibl"
    raw: cd ansibl

  - name: "touch"
    raw: touch 1.txt

