---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: "cd"
    raw: cd /home/bazar/git

  - name: "rm"
    raw: rm -rf  ansibl

  - name: "Git clone"
    raw: git clone https://github.com/Sergo2019/ansibl.git
   
  - name: "cd ansibl"
    raw: cd ansibl

