---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - name: "mkdir"
    raw: mkdir /home/bazar/git

  - name: "cd"
    raw: cd /home/bazar/git

  - name: "Git clone"
    raw: git clone https://github.com/Sergo2019/ansibl.git
   
  - name: "cd ansibl"
    raw: cd ansibl

