 
---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo
  
  tasks:

  - name: "mkdir"
    raw: mkdir /home/bazar/git
  - name: "cd"
    raw: cd /home/bazar/git
  - name: "init"  
    raw: git init
  - name: "git config" 
    raw: git config --global user.email "sgibnevsergei@gmail.com"
    raw: git config --global user.name "sergo2019"
  - name: "add rep" 
    raw: git remote add origin https://github.com/Sergo2019/sergo.git
  - name: "git pull" 
    raw: git pull origin master && git push origin master 
    become: yes

