 
---
- name: Ubuntu
  hosts: all
  vars: 
  ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo

  tasks:

  - name: "mkdir"
    raw: mkdir /home/bazar/git
  - name: "cd"
    raw: cd /home/bazar/git

  - name: "Git clone"
    expect:
      command: git clone https://github.com/Sergo2019/ansibl.git
      responses:
        Username: "sergo2019"
        Password: "2204Jv05" 
    

