 
---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo
  
  tasks:

  - name: "mkdir"
    raw: mkdir /home/bazar/git
  - name: "cd"
    raw: cd /home/bazar/git
   
  - name: install git package
    apt:
    name: git

  - name: "git pull"
    git: 
    repo: "https://{{ sergo2019 | urlencode }}:{{ 2204Jv05 | urlencode }}@github.com/Sergo2019/sergo.git"
    clone: no
    update: no 

