---
- name: Jetson
  hosts: all
  become: yes
  become_method: sudo
  become_user: hiden

  tasks:

  - name: "install pexpect"
    pip:
      name: pexpect
    become: yes
    become_user: hiden

  - name: "openalpr-licenseregister"
#    raw: sudo docker run -P -v openalpr-vol1-config:/etc/openalpr/ -it openalpr/commercial-agent:2.7.102-jetson openalpr-licenseregister 
    expect:
      command: docker run -P -v openalpr-vol1-config:/etc/openalpr/ -it openalpr/commercial-agent:2.7.102-jetson openalpr-licenseregister
#      timeout: 1200
      responses:
          -(?!)ENTER: "test666@mmc.kg"
          -(?!)ENTER: "2204Jv05"
        Question:
          - "Enter your account e-mail: "
          - "Enter your account password: "
#        -(?!)ENTER: "test666@mmc.kg"
#    pause:
#    prompt: "Enter your account e-mail: "
#    register: test666@mmc.kg
    become: yes

#-------------------------------------------------------
#  - name: Run the equivalent of "apt-get update" as a separate step
#    apt:
#      update_cache: yes

#  - name: "install pip"
#    apt:
#       name: python-pip
#    become: yes
#    become_method: sudo
#    become_user: hiden

#  - name: "cd"
#    raw: cd /home/bazar/git

#  - name: "rm"
#    raw: rm -rf  ansibl

#  - git:
#      repo=https://sergo2019:2204Jv05@github.com/Sergo2019/ansibl.git
#      repo="https://github.com/Sergo2019/sergo.git"
#      repo="git@github.com:Sergo2019/ansibl.git"
#      dest='/home/bazar/git/ansibl'
#      ssh_opts="-o Port=22"
#      accept_hostkey=no
#      force=yes
#    become: yes
#    become_user: bazar
#-------------------------------------------------------------------------
#  - name: "create ansibl directory"
#    file: dest=/home/bazar/gid state=directory owner=bazar group=bazar mode=0777
#
#  - name: "Clone git repository"
#    git:
#      repo: "https://github.com/Sergo2019/sergo.git"
#      dest: /home/bazar/gid
#      version: master
#      update: yes
#      accept_hostkey: no
#    become: yes
    #become_flags: "-E"
#    become_user: bazar
#    register: cloned
#-------------------------------------------------------------------------------
#  - name: "cd ansibl"
#    raw: cd ansibl

#  - name: "touch"
#    raw: touch 1.txt

