---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: "cd"
    raw: cd /home/bazar/git

  - name: "rm"
    raw: rm -rf  ansibl

  - name: "git clone" 
    git: >
      repo=https://sergo2019:2204Jv05@github.com/Sergo2019/ansibl.git
      dest=/home/bazar/git/ansibl
    become_user: bazar

  - name: "cd ansibl"
    raw: cd ansibl

  - name: "touch"
    raw: touch 1.txt

