---
- name: Ubuntu
  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: "cd"
    raw: cd /home/bazar/git

  - name: "rm"
    raw: rm -rf  ansibl

  - name: "git clone" 
    git: >
      repo=ssh://git@github.com:Sergo2019/ansibl.git
      dest=/home/bazar/git/ansibl


  - name: "cd ansibl"
    raw: cd ansibl

  - name: "touch"
    raw: touch 1.txt

